### ISSUE TITLE
Style the Resources page

### ISSUE THREAD

**Issue by ANDREYDEN** [gdsc-conestoga/website#17]
The Resources page should list links mentioned in [this](https://docs.google.com/document/d/1fkaTzob9xHglfr85g30PdW8Nv7wcwz9Doi1lZC_0rbE/edit?usp=sharing) Google Doc.

Each link should have an appropriate icon and a description.

**Comment by larrycoal** [comment]
will like to work on this @ANDREYDEN

**Comment by ANDREYDEN** [comment]
Hi @larrycoal, I can see that you are not a member of our GitHub organization, are you a member of the GDSC Conestoga club? If so, can you please send me your Conestoga email so that I can verify and add you to the org? I'm trying to prioritize contributions from the club members

**Comment by larrycoal** [comment]
hello @ANDREYDEN i am a member of the github organization and a member of the club,dm you on discord and you added me, not sure where the confusion is coming from, but will send you a message on discord

**Comment by ANDREYDEN** [comment]
I'm so sorry, I must've missed you when I was checking the org members list. My bad, adding you to this issue
