### ISSUE TITLE
Style the header menu

### ISSUE THREAD

**Issue by ANDREYDEN** [gdsc-conestoga/website#22]
The header menu should look nicer both on mobile and desktop

Desktop:
- [ ] add a clickable GDSC logo (top-left of the page) that navigates to the home page

Mobile:
- [ ] display a hamburger menu that slides into view

All platforms:
- [ ] a menu item should be highlighted/underlined if the user navigates to the corresponding page

**Comment by Ellipticamit** [comment]
@ANDREYDEN  Should i use custom css or can i add tailwindcss to make the ui better

**Comment by ANDREYDEN** [comment]
Hi @Ellipticamit, custom CSS is preferred as we try to focus on React in the sessions and bring to many libs in. I would say give it a try with CSS, if things will get ugly - we can go with Tailwind

**Comment by Ellipticamit** [comment]
@ANDREYDEN  Created a PR. https://github.com/gdsc-conestoga/website/pull/24

**Comment by KannuSingh** [comment]
@ANDREYDEN Is this still up for grab/open?

**Comment by ANDREYDEN** [comment]
@KannuSingh, this was closed in #24
