### ISSUE TITLE
Style the add-event modal

### ISSUE THREAD

**Issue by ANDREYDEN** [gdsc-conestoga/website#28]
Style the modal to add a new event:
![image](https://user-images.githubusercontent.com/25109066/157329772-710c1dda-4c82-4aea-bae9-a05d5df3d6d1.png)

Make sure to only style the form:
- change the size of the modal - make it smaller
- change the colors (optional)
- add a title to the modal

We are using `react-modal`, but feel free to use a different library or come up with your own solution from scratch

**Comment by annetawamono** [comment]
Hi, I'd like to take up this task. Do you have a due date for it?

**Comment by ANDREYDEN** [comment]
Hi @annetawamono, no due date, but I'll happily assign you for this ticket
