### ISSUE TITLE
Add pages with react-router

### ISSUE THREAD

**Issue by ANDREYDEN** [gdsc-conestoga/website#3]
We need to set up react router and build a basic navigation menu to switch between some basic pages:
- [ ] Home page
- [ ] Resources page
- [ ] Calendar page
- [ ] Blog page

**Comment by larrycoal** [comment]
Will be working on this

**Comment by ANDREYDEN** [comment]
Hi @larrycoal, what exactly do you want to work on? I was thinking to set up `react-router` and do some basic scaffolding during our next session. We can discuss what other features you could take on.

**Comment by larrycoal** [comment]
oh alright then
