### ISSUE TITLE
Dark/Light theme

### ISSUE THREAD

**Issue by ANDREYDEN** [gdsc-conestoga/website#5]
Enable switching between a light and a dark theme

**Comment by Ellipticamit** [comment]
@ANDREYDEN If it's open i like to take this issue.

**Comment by ANDREYDEN** [comment]
Hi @Ellipticamit, this possibly might be a session content ticket. I will update you in case I won't be covering this during one of my sessions. Meanwhile, I suggest you look at other tickets with the `up-for-grabs` label.
