### ISSUE TITLE
Style the home page

### ISSUE THREAD

**Issue by ANDREYDEN** [gdsc-conestoga/website#8]
- [x] Replace the rotating logo with our GDSC logo
- [x] Change the text to our club's description
- [x] Change the page icon to the GDSC icon

**Comment by SubhajitS** [comment]
Hey folks, I can help with this.

**Comment by ANDREYDEN** [comment]
Hi @SubhajitS, are you a member of our Conestoga GDSC club? 
- If so, I'll add you to our organization. 
- If not, currently we are prioritizing contributions from club members. If no one will take this issue in the closest couple of days, I'll assign you to tackle this.

**Comment by ifefrost** [comment]
Hi, I can take this task.

**Comment by ANDREYDEN** [comment]
Awesome, @ifefrost, I'm assigning you to this issue
